### ISSUE TITLE
运行的攻击成功率与论文不一致

### ISSUE THREAD

**Issue by QienJane** [lbinmeng/EEG_poisoning_attack#4]
**博主您好！我按照您的论文中对MI数据的攻击算法进行了对齐，但是发现攻击成功率ASR一直为0，达不到您论文中的攻击成功率，冒昧向您咨询一下可能得原因是什么呢？还请您不吝赐教！**
![image](https://user-images.githubusercontent.com/84821239/233894098-9d4f05b1-b6e0-4be7-82bd-23065c663129.png)

**Comment by lbinmeng** [comment]
> **博主您好！我按照您的论文中对MI数据的攻击算法进行了对齐，但是发现攻击成功率ASR一直为0，达不到您论文中的攻击成功率，冒昧向您咨询一下可能得原因是什么呢？还请您不吝赐教！**
> ![image](https://user-images.githubusercontent.com/84821239/233894098-9d4f05b1-b6e0-4be7-82bd-23065c663129.png)

你肯定是没调扰动幅值，默认是P300上的幅值0.003。还请你认真看论文和代码，后续遇到问题还请你自己多思考
